site_name: Password Generator Module
site_description: Generate passwords quickly with this incredible module.

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      handler: python

nav:
  - Introduction: index.md