site_name: Password Generator Module
site_description: Generate passwords quickly with this incredible module.

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/frit-apps/password-generator-module
repo_name: frit-apps/password-generator-module


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition


plugins:
  - search
  - mkdocstrings:
      handler: python

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frit-apps/password-generator-module

copyright: Copyright &copy; 2021 Frit Apps Organization

nav:
  - Home: index.md
  - Get started:
    - 'Examples': 'get_started.md'
    - 'Code references': 'pgm-reference.md'
  - Download: 'download.md'
  - About:
    - 'PGM Project': 'about.md'
    - 'Change Log': 'CHANGELOG.md'
    - 'License': 'LICENSE.md'